# Load data from database
use_database: false

# Data directory containing day_dic files
data_dir: ../ppcx_dic/output/2020/correlation/day_dic_ensemble_h5 #data/h5/ # data/day_dic/

# File glob pattern
file_search_pattern: "*"

# Filename template to extract intiial and final dates from filenames.
# Template matches the file *stem* (filename without extension).
# Use placeholders: {final:<strftime>} and {initial:<strftime>}.
# Examples:
# - day_dic_20230104-20230101.txt -> "day_dic_{final:%Y%m%d}-{initial:%Y%m%d}"
# - dic_20230104_20230101.txt     -> "dic_{final:%Y%m%d}_{initial:%Y%m%d}"
# - 20230104-20230101_dic.txt     -> "{final:%Y%m%d}-{initial:%Y%m%d}_dic"
# filename_date_template: "day_dic_{final:%Y%m%d}-{initial:%Y%m%d}"
filename_date_template: "day_dic_{final:%Y-%m-%d}_{initial:%Y-%m-%d}_*"

# Background image path (optional)
# background_image: ./data/PPCX_2_2021_08_03_13_01_02.jpg 
# Otherwise set to null to disable background image
background_image: null #"./data/PPCX_2_2021_08_03_13_01_02.jpg"

# Results output directory
# results_dir: ./results

# Data settings
dt_days: [1, 3,5]  # Set to an integer (e.g., 3) or to a list of integer (e.g., [3,5]) to filter by preferred time delta in days or null to keep all
dt_hours_tolerance: 20  # Allowed deviation from preferred dt_days in hours
invert_y: false # Invert Y axis in plots

# Parallel processing
max_workers: 8  # Maximum number of workers for file loading

# log level
log_level: "DEBUG"

# Database connection (if use_database is true)
# db_host: "150.145.51.193"
# db_port: 5434
# db_name: "planpincieux"
# db_user: "postgres"
# db_password: ""  # Better to keep in .env or as env var

# API connection (if use_api is true)
# use_api: false
# api_host: "150.145.51.193"
# api_port: 8080

# Overwrite guinicorn server settings
# host: 0.0.0.0
# port: 8000
# debug: true